triggers:
  - type: meya.keyword
    properties:
        ignorecase: true
        keyword: _cto_
states:
    opening:
        component: meya.text
        properties:
            text: "Ok. Sounds like you need to make changes to your timesheet 🕖.  I'd be happy to help you with that."
        delay:
            relative: 1
    explain_rules:
        component: meya.text
        properties:
            text: "You have the ability to edit your time unless timesheets are locked for payroll processing (from the timesheet deadline for the period until the following Wednesday morning)"
    calculate_date: # This is the date after which an employee can't make changes themselves
        component: timesheet_cutoff
    before_or_after_state:
        component: meya.text_buttons
        properties:
            text: "In what pay period do you need to make a change?"
            output: time_sheet_before_or_after
            buttons:
                - text: "Ending on or before {{flow.timesheet_date_cutoff}}"
                  action: after_cutoff
                - text: "Current pay period or later."
                  action: before_cutoff
        transitions:
            after_cutoff: after_cutoff
            before_cutoff: before_cutoff_opening
    before_cutoff_opening:
        component: meya.text
        properties:
            text: "No problem.  I can walk you through how to make a timesheet change."
    before_cutoff_time_type:
        component: meya.text_buttons
        properties:
            text: "What kind of time entry are you looking to fix?"
            output: time_sheet_work_or_timeoff
            buttons:
                - text: "Time away from work (vacation, bereavement)"
                  action: time_away
                - text: "Work hours"
                  action: work_hours
        transitions:
            time_away: time_away
            work_hours: work_hours
    time_away:
        component: me ya.text
        properties:
            text: "Lets correct your time away"
        return: true
    work_hours:
        flow: timesheet_work_hours
        transitions:
            request_feedback: request_feedback
    request_feedback:
        component: meya.text_buttons
        properties:
            text: "Did I answer your question for you?"
            output: time_sheet_feedback
            buttons:
                - text: "Yes!"
                  action: yes
                - text: "No, I still need help 😟"
                  action: no
        transitions:
            yes: yes_feedback_state
            no: no_feedback_state
    yes_feedback_state:
        component: meya.text
        properties:
            text: "That's great to hear!"
        delay:
            relative: 1
        return: true
    no_feedback_state:
        component: meya.text
        properties:
            text: "I'm sorry to hear!"
        delay:
            relative: 1
        return: true
    after_cutoff:
        component: meya.text
        properties:
            text: "Let me connect you with our support team to help."
        return: true