triggers:
  - type: meya.keyword
    properties:
        ignorecase: true
        keyword: _cto_
states:
    opening:
        component: meya.text
        properties:
            text: "Ok. Sounds like you need to make changes to your timesheet 🕖.  I'd be happy to help you with that."
    calculate_date: # This is the date after which an employee can't make changes themselves
        component: timesheet_cutoff
    before_or_after_state:
        component: meya.text_buttons
        properties:
            text: "In what pay period do you need to make a change?"
            output: time_sheet_before_or_after
            buttons:
                - text: "Ending on or before {{flow.timesheet_date_cutoff}}"
                  action: after_cutoff
                - text: "Current pay period or later."
                  action: before_cutoff
        transitions:
            after_cutoff: after_cutoff
            before_cutoff: before_cutoff
    before_cutoff:
        component: meya.text
        properties:
            text: "No problem.  I can walk you through how to make a timesheet change."
        return: true
    after_cutoff:
        component: meya.text
        properties:
            text: "Let me connect you with our support team to help."
        return: true