triggers:
  - type: meya.keyword
    properties:
        ignorecase: true
        keyword: _cto_
name: correct_time_off
states:
    say_opening:
        component: meya.text
        properties:
            text: "{{ cms.time_off.intro }}"
        delay:
            relative: 1
    
    say_rules:
        component: meya.text
        properties:
            text: "{{ cms.time_off.rules }}"

    calculate_date: # This is the date after which an employee can't make changes themselves
        component: timesheet_cutoff

    ask_pay_period:
        component: meya.text_buttons
        properties:
            text: "{{ cms.time_off.ask_pay_period }}"
            output: time_sheet_before_or_after
            buttons:
                - text: "Ending on or before {{flow.timesheet_date_cutoff}}"
                  action: after_cutoff
                - text: "Current pay period or later."
                  action: before_cutoff
        transitions:
            after_cutoff: say_after_cutoff
            before_cutoff: say_before_cutoff

    say_before_cutoff:
        component: meya.text
        properties:
            text: "{{ cms.time_off.before_cutoff }}"

    say_before_cutoff_time_type:
        component: meya.text_buttons
        properties:
            text: "{{ cms.time_off.before_cutoff_time_type }}"
            output: time_sheet_work_or_timeoff
            buttons:
                - text: "Time away from work (e.g. vacation, bereavement)"
                  action: time_away
                - text: "Work hours"
                  action: work_hours
        transitions:
            time_away: say_time_away
            work_hours: goto_timesheet_work_hours

    time_away:
        flow: timesheet_time_away
        transitions:
            request_feedback: request_feedback

    goto_timesheet_work_hours:
        flow: timesheet_work_hours
        transitions:
            request_feedback: request_feedback

    ask_feedback:
        component: meya.text_buttons
        properties:
            text: "{{ cms.time_off.ask_feedback }}"
            output: time_sheet_feedback
            buttons:
                - text: "Yes!"
                  action: yes
                - text: "No, I still need help 😟"
                  action: no
        transitions:
            yes: yes_feedback
            no: no_feedback

    yes_feedback:
        component: meya.text
        properties:
            text: "{{ cms.time_off.feedback_positive }}"
        delay:
            relative: 1
        return: true

    no_feedback:
        component: meya.text
        properties:
            text: "{{ cms.time_off.feedback_negative }}"
        delay:
            relative: 1
        return: true

    say_after_cutoff:
        component: meya.text
        properties:
            text: "{{ cms.time_off.after_cutoff }}"
        return: true