triggers:
  - type: meya.start_chat
name: welcome
states:
    opening_line:
        component: meya.text
        properties:
            text: '{{cms.greetings.opening_line}}'
        delay:
            relative: 1
    call_to_action_prompt:
        component: meya.text
        properties:
            text: '{{cms.greetings.call_to_action}}'
        return: true