triggers:
  - type: meya.start_chat
  - type: meya.greetings
name: welcome
states:
    opening_line:
        component: meya.text
        properties:
            text: '{{cms.greetings.opening_line}}'
        delay:
            relative: 2
    call_to_action:
        component: meya.input_cms
        properties:
            text: '{{cms.greetings.call_to_action}}'
            space: "navigation_nlp"
            key: "benefits"
            require_match: false
            min_confidence: 0.8
            detect_language: true
        transitions:
            benefits: benefits_state
            no_match: navigation_undetected1
    navigation_undetected1:
        component: meya.text
        properties:
            text: Bad
        return: true
    benefits_state:
        flow: benefits_flow
        properties:
            text: Good
        return: true